### ISSUE TITLE
bosh2 events returns 0 events - what should it return?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#104]
Pointing `bosh2 events` at my bosh-lite running latest bosh release, I get 0 events. Is that right? Or what should I see? Something I need to enable on my director?

```
$ bosh2 events
Using environment 'https://10.58.111.48:25555' as user 'admin'

ID  Time  User  Action  Object Type  Object ID  Task ID  Deployment  Instance  Context

0 events

Succeeded
```

**Comment by cppforlife** [comment]
@drnic try out `BOSH_LOG_LEVEL=debug` and see what you get. make sure you are using updated bosh-lite (events should be enabled there: https://github.com/cloudfoundry/bosh-lite/blob/master/packer/templates/bosh_lite_manifest_template.yml#L77)

**Comment by drnic** [comment]
Ok, thanks for pointer to director config. Rolling that out now across our bosh-lites.

**Comment by ljfranklin** [comment]
@cppforlife can we re-open this? Feels like we need some help text or error from the events command if events are turned off, e.g. "The Director is currently not configured to record events. Enable this feature by adding `jobs.bosh.properties.director.events.record_events: true` to your director manifest".
