### ISSUE TITLE
manifest.yml cannot use YAML aliases

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#12]
If my bosh-init deployment manifest includes YAML aliases (`&` and `*`), the `bosh-init deploy` hangs:

```
Started validating
  Validating stemcell... Finished (00:00:00)
  Validating releases... Finished (00:00:02)
  Validating deployment manifest...^C^C
```

**Comment by drnic** [comment]
@cppforlife

**Comment by cppforlife** [comment]
That's weird. I've been using aliases in the manifest for some time. Are you compiling with golang 1.4?

**Comment by drnic** [comment]
I'm unsure about what caused this - I've seen aliases work as well.




It was concourse-lite manifest that caused the grief; and the panics went away when I untangled the aliases.

**Comment by cppforlife** [comment]
Possibly bash was messing with your manifest?

**Comment by cppforlife** [comment]
closing. we have migrated to goyaml since then and i've used yaml references successfully.
