### ISSUE TITLE
CPI  'create_stemcell' method responded with error

### ISSUE THREAD

**Issue by shivamvarma** [cloudfoundry/bosh-init#125]
I am trying to setup bosh CPI environment on vsphere and I am getting the following error:-
 creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3421.9):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"getaddrinfo: Name or service not known (esxi-18.test.hytrust.com:443)","ok_to_retry":false}
please let know how do I fix it.

**Comment by mssh2001** [comment]
exact same problem for me

**Comment by mssh2001** [comment]
exact same problem for me

**Comment by prashantgnet** [comment]
same issue for me as well

**Comment by prashantgnet** [comment]
Issue solved after changing dns entry under bosh.yml to local DNS server.

**Comment by dpb587-pivotal** [comment]
This error usually means DNS has not been correctly configured. If using [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment), you can use the [misc/dns.yml](https://github.com/cloudfoundry/bosh-deployment/blob/master/misc/dns.yml) ops file to specify your own internal DNS servers.

    bosh create-env bosh.yml -o misc/dns.yml -v internal_dns=[10.0.0.10,10.0.10.10] ...

To investigate and verify further, you could connect to the failing VM and manually verify connectivity with `dig`/`curl`.

**Comment by abhilash07** [comment]
Hi @prashantgnet & @dpb587-pivotal  thank for your suggestions, i am trying to deploying Micro-bosh on vsphere 6.5.

But i encounter below error

creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3468.21):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"getaddrinfo: Name or service not known (cl3-esx01.cl2.local:443)","ok_to_retry":false}

Exit code 1


After searching i find the similar issue #125 i follow the same instructions. I dig the host domain name in my vm and change the dns in bosh.yml file. @prashantgnet
![screen shot 2018-03-13 at 2 16 38 pm](https://user-images.githubusercontent.com/10971841/37323837-717dcf62-26c9-11e8-8f10-46fcf54c96cc.png)
![screen shot 2018-03-13 at 2 17 47 pm](https://user-images.githubusercontent.com/10971841/37323839-73955c8e-26c9-11e8-9012-209f3109009a.png)
![screen shot 2018-03-13 at 2 18 14 pm](https://user-images.githubusercontent.com/10971841/37323842-75323576-26c9-11e8-8aac-70961578dd56.png)

My Bosh Command

bosh create-env ~/workspace/bosh-deployment/bosh.yml 
--state=/home/ubuntu16-04/workspace/bosh-deployment/git/state.json 
--vars-store=/home/ubuntu16-04/workspace/bosh-deployment/git/creds.yml 
-o ~/workspace/bosh-deployment/vsphere/cpi.yml -o ~/workspace/bosh-deployment/local-dns.yml 
-o ~/workspace/bosh-deployment/dns-addresses.yml -v director_name=VMware-Boot-Strapper 
-v internal_cidr=172.16.15.0/24 -v internal_gw=172.16.15.1 -v internal_ip=172.16.15.155 -v network_name="VM Network" -v vcenter_dc=CL3-DC -v vcenter_ds=Local_SAS -v vcenter_ip=172.16.15.201 -v vcenter_user=xxxxx -v vcenter_password='xxxxxx' -v vcenter_templates=paasxpert-templates -v vcenter_vms=paasxpert-vms -v vcenter_disks=paasxpert-disks -v vcenter_cluster=CL3-HA

but i can login and create template folder and start uploading stemcell 

<img width="1172" alt="screen shot 2018-03-13 at 2 21 43 pm" src="https://user-images.githubusercontent.com/10971841/37323947-05e74b2e-26ca-11e8-9d08-fae61e752a7b.png">

is there any thing i have to change, please let know how do I fix it.

Thank in advance.

Abhilash S
