### ISSUE TITLE
Bosh director deployment issue with Vsphere and Centos

### ISSUE THREAD

**Issue by Velann** [cloudfoundry/bosh-init#130]
When i try to deploy bosh director on and create VM in vsphere below error occurred, Please guide me to get it resolved.

stemcell used : bosh-stemcell-3468.11-vsphere-esxi-centos-7-go_agent.tgz

[root@linbgg219 ~]# bosh create-env bosh-1/bosh-deployment/bosh.yml     --state=state.json     --vars-store=credentials.yml     -o bosh-1/bosh-deployment/vsphere/cpi.yml     -v director_name=bosh-1     -v internal_cidr=10.31.116.240/28     -v internal_gw=10.31.116.241     -v internal_ip=10.31.116.252     -v network_name="VM Network"     -v vcenter_dc=datacenter1     -v vcenter_ds=vnx-m179-lun23-smarts     -v vcenter_ip=10.31.149.104     -v vcenter_user=administrator@vsphere.local     -v vcenter_password=Dangerous@123     -v vcenter_templates=win2k-template     -v vcenter_vms=bosh-1-vms     -v vcenter_disks=Test     -v vcenter_cluster=cluster1
Deployment manifest: '/root/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bosh-vsphere-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:05)
Finished validating (00:00:07)

Started installing CPI
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Finished (00:00:00)
  Compiling package 'vsphere_cpi/e978df2abd6124573d76f4a204570cde9d4d429e'... Finished (00:00:00)
  Compiling package 'iso9660wrap/82cd03afdce1985db8c9d7dba5e5200bcc6b5aa8'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-centos-7-go_agent/3468.11'... Finished (00:09:36)

Started deploying
  Waiting for the agent on VM 'vm-fd58e72a-86ab-49ab-a6d9-7ae81541c461'... Failed (00:00:30)
  Deleting VM 'vm-fd58e72a-86ab-49ab-a6d9-7ae81541c461'... Finished (00:00:08)
  Creating VM for instance 'bosh/0' from stemcell 'sc-321717fd-df6e-4bda-b402-321ffedb07cb'... Finished (00:00:14)
  Waiting for the agent on VM 'vm-b2c43460-5827-4fa1-b8da-974dec0e431f' to be ready... Finished (00:01:43)
  Creating disk... Finished (00:00:04)
  Attaching disk 'disk-b4b2c0c1-a462-452a-8f79-fa0346e14fc0' to VM 'vm-b2c43460-5827-4fa1-b8da-974dec0e431f'... Finished (00:00:19)
  Rendering job templates... Finished (00:00:04)
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Finished (00:04:14)
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Skipped [Package already compiled] (00:00:06)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Skipped [Package already compiled] (00:00:05)
  Compiling package 'libpq/826813f983d38b4b4a95bb8a3df1a2d0efab14b0'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'iso9660wrap/82cd03afdce1985db8c9d7dba5e5200bcc6b5aa8'... Finished (00:00:02)
  Compiling package 'davcli/2672d0a96a775f5252fef6ac7bbab3928aa41599'... Skipped [Package already compiled] (00:00:01)
  Compiling package 'gonats/866cdc573ac10dd85929abb531923197486ffa95'... Skipped [Package already compiled] (00:00:02)
  Compiling package 'postgres-9.4/1da82648840de67015d379264846a447118261a7'... Skipped [Package already compiled] (00:00:07)
  Compiling package 'vsphere_cpi/e978df2abd6124573d76f4a204570cde9d4d429e'... Failed (00:00:21)
Failed deploying (00:08:18)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Building state for instance 'bosh/0':
    Compiling job package dependencies for instance 'bosh/0':
      Compiling job package dependencies:
        Remotely compiling package 'vsphere_cpi' with the agent:
          Sending 'compile_package' to the agent:
            Sending 'get_task' to the agent:
              Agent responded with error: Action Failed get_task: Task 83dd793f-854b-4361-6721-c70fd9d2a7cf result: Compiling package vsphere_cpi: Running packaging script: Running packaging script: Command exited with 1; Stdout: , Stderr: + BOSH_PACKAGES_DIR=/var/vcap/packages
+ cp -a vsphere_cpi/Gemfile vsphere_cpi/Gemfile.lock vsphere_cpi/bin vsphere_cpi/lib vsphere_cpi/vendor /var/vcap/packages/vsphere_cpi
+ export BUNDLE_CACHE_PATH=vendor/package
+ BUNDLE_CACHE_PATH=vendor/package
+ export BUNDLE_WITHOUT=development:test
+ BUNDLE_WITHOUT=development:test
+ bundle_cmd=/var/vcap/packages/ruby-2.4/bin/bundle
+ cd /var/vcap/packages/vsphere_cpi
+ /var/vcap/packages/ruby-2.4/bin/bundle install --local --no-prune --deployment
/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/digest.rb:16:in `const_missing': library not found for class Digest::MD5 -- digest/md5 (LoadError)
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/source/rubygems/remote.rb:26:in `cache_slug'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/fetcher/compact_index.rb:107:in `cache_path'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/fetcher/compact_index.rb:83:in `compact_index_client'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:646:in `warn_on_outdated_bundler'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:24:in `block in dispatch'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:366:in `dispatch'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from /var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
        from /var/vcap/packages/ruby-2.4/bin/bundle:22:in `load'
        from /var/vcap/packages/ruby-2.4/bin/bundle:22:in `<main>'

Exit code 1

**Comment by Velann** [comment]
Some how the above error is solved but now stuck at the below one.

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-954263e4-4497-441f-a204-3d323bacbb44'... Finished (00:00:13)
  Waiting for the agent on VM 'vm-29a32230-6dc0-47db-9e5e-b8873075ed13' to be ready... Finished (00:01:45)
  Creating disk... Finished (00:00:04)
  Attaching disk 'disk-a01cc656-ab0c-43a5-9fc8-ac3a5e606a18' to VM 'vm-29a32230-6dc0-47db-9e5e-b8873075ed13'... Finished (00:00:18)
  Rendering job templates... Finished (00:00:04)
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Skipped [Package already compiled] (00:00:07)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Skipped [Package already compiled] (00:00:05)
  Compiling package 'libpq/826813f983d38b4b4a95bb8a3df1a2d0efab14b0'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'ruby-2.4/cff0ddb99e62cd9dfa146248dcbfd6df2a62a54e'... Finished (00:04:17)
  Compiling package 'gonats/866cdc573ac10dd85929abb531923197486ffa95'... Skipped [Package already compiled] (00:00:02)
  Compiling package 'verify_multidigest/8fc5d654cebad7725c34bb08b3f60b912db7094a'... Skipped [Package already compiled] (00:00:00)
  Compiling package 'director/9ada78066fd25b6708c42e1e34cd384ac9362135'... Skipped [Package already compiled] (00:00:18)
  Compiling package 'nginx/57ca1d048957399c500e0f5fd3275ed4c6d4f762'... Skipped [Package already compiled] (00:00:02)
  Compiling package 'vsphere_cpi/e978df2abd6124573d76f4a204570cde9d4d429e'... Finished (00:01:53)
  Compiling package 'postgres-9.4/1da82648840de67015d379264846a447118261a7'... Skipped [Package already compiled] (00:00:07)
  Compiling package 'iso9660wrap/82cd03afdce1985db8c9d7dba5e5200bcc6b5aa8'... Finished (00:00:02)
  Compiling package 'bosh-gcscli/fce60f2d82653ea7e08c768f077c9c4a738d0c39'... Skipped [Package already compiled] (00:00:03)
  Compiling package 'davcli/2672d0a96a775f5252fef6ac7bbab3928aa41599'... Skipped [Package already compiled] (00:00:01)
  Compiling package 'health_monitor/2c4257e86f3b26cd2f5e6c7b393cc0ae1d366e87'... Skipped [Package already compiled] (00:00:09)
  Compiling package 'postgres/3b1089109c074984577a0bac1b38018d7a2890ef'... Skipped [Package already compiled] (00:00:06)
  Compiling package 's3cli/b6e38c619dd5575e16ea9fcabc4b7c500effdd26'... Skipped [Package already compiled] (00:00:02)
  Updating instance 'bosh/0'... Finished (00:00:15)
  Waiting for instance 'bosh/0' to be running... Failed (00:05:11)
Failed deploying (00:15:22)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Received non-running job state: 'starting'

Exit code 1

**Comment by dpb587-pivotal** [comment]
Hi - sorry this appears to have been lost. We don't currently test director running on CentOS (only Ubuntu). I'd recommend taking a look at and using [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) in the future.

This `bosh-init` repository is older - the docs in bosh-deployment provide more references to the replacement of `bosh create-env ...`.

I'm going to close this, but feel free to create followup issues in bosh-deployment if you have trouble using it.

**Comment by mllives** [comment]
@dpb587-pivotal Hi.I am also encounter this issue that "Waiting for instance 'bosh/0' to be running... Failed", I don't know why. I would appreciate it if you can help me out!
