### ISSUE TITLE
Please add persistent_disk_pool into example manifest

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#16]
https://github.com/cloudfoundry/bosh-init/blob/master/docs/cli_workflow.md - the example manifest doesn't describe a persistent disk

**Comment by drnic** [comment]
Does bosh-init support the old and new formats for persistent_disk? https://bosh.io/docs/persistent-disks.html

**Comment by cppforlife** [comment]
It should. Did you run into some error?

**Comment by drnic** [comment]
I was busy cargo culting and forgot to add persistent_disk to my job.




I'll patch it.

**Comment by cppforlife** [comment]
bosh.io docs for bosh-init use persistent disk pool for examples.
