### ISSUE TITLE
Issue with deploy command: Invalid usage - deploy command requires exactly 2 arguments.

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh-init#21]
Hey, all.

I can't get `deploy` command run because of a strange output. After I call `bosh-init deploy` with manifest, stemcell, cpi and bosh release it says that `deploy` should take only 2 arguments:

```
→ bosh-init deploy manifests/bosh-micro-manifest.yml stemcells/bosh-stemcell.tgz releases/cpi-release.tgz releases/bosh-release.tgz
[deployCmd] 2015/04/19 22:13:14 ERROR - Invalid arguments: []string{"manifests/bosh-micro-manifest.yml", "stemcells/bosh-stemcell.tgz", "releases/cpi-release.tgz", "releases/bosh-release.tgz"}
[main] 2015/04/19 22:13:14 ERROR - Command 'deploy' failed: Invalid usage - deploy command requires exactly 2 arguments
... <help output>
```

After I try to do it in the [way that is used in tests](https://github.com/cloudfoundry/bosh-init/blob/30bf29d74dd828d74a8d2e42fcdb9bcf05d2bc09/acceptance/lifecycle_test.go#L87) using only manifest and stemcell, I get following error: 
```
Command 'deploy' failed:
  Validating release set manifest:
    releases must contain at least 1 release
```

I needed to checkout to 8c27d326388324349cb5ed18a1536cfa15215b1c hash key to fix this problem.

I think it's not a big issue and it will be fixed soon. Could you tell if you plan to change interface of `deploy` command?

Best wishes,
Alex L.

**Comment by cppforlife** [comment]
We are currently in transition to specifying releases/stemcells via the manifest. Master probably has releases implemented. This commit looks like a beginning: https://github.com/cloudfoundry/bosh-init/commit/179d5f1204d4b31f31822fe9c93a7ef1d23b002b.

**Comment by allomov** [comment]
That's ok, will use previous version for now.
