### ISSUE TITLE
v0.0.1 tagged after v0.0.7

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#25]
https://github.com/cloudfoundry/bosh-init/releases - bug in ci pipeline?

**Comment by cppforlife** [comment]
Will be fixed after https://www.pivotaltracker.com/story/show/93295300

**Comment by bosh-init-concourse** [comment]
This is likely a result of tags added while working on the new concourse
pipeline for bosh-init.  Perhaps we should go back and clean up the
previous, higher version tags.

Corey

On Sat, Apr 25, 2015 at 8:30 AM, Dr Nic Williams <notifications@github.com>
wrote:

> https://github.com/cloudfoundry/bosh-init/releases - bug in ci pipeline?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-init/issues/25>.
>



-- 

[image: --]
Corey Innis
[image: http://]about.me/coreyti
<http://about.me/coreyti?promo=email_sig>

**Comment by drnic** [comment]
I'm ok with any fix fwiw
