### ISSUE TITLE
Can we please add pre-compiled bosh-init into releases?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-init#26]
I'm trying to do pipelining to ensure the `bosh-init-redis`, `*-bosh`, etc projects keep working for new version of `bosh-init` based on releases.

Creating ticket so @cppforlife can let me know when releases (rather than tags) are being uploaded so I can simplify my pipelines. Currently will trigger pipeline based on any git commit (afaik thats all git-resource can do)

**Comment by cppforlife** [comment]
We have two buckets that bosh-init binaries are published. See these two resources for the location: https://concourse-1739433260.us-east-1.elb.amazonaws.com/resources/release-bucket-linux and https://concourse-1739433260.us-east-1.elb.amazonaws.com/resources/release-bucket-darwin
