### ISSUE TITLE
discrepancy in bosh-init tutorial 

### ISSUE THREAD

**Issue by mavenraven** [cloudfoundry/bosh-init#31]
[I'm guessing this document is actually in https://github.com/cloudfoundry/docs-bosh somewhere, but I can't find it]

Hey @cppforlife ,
In https://bosh.io/docs/init-aws.html, the deployment manifest uses 10.10.0.0/24 for the subnet. However, the screenshots use 10.0.0.0/16 for the VPC and 10.0.0.0/24 for the subnet on AWS. It looks like the example manifest should be switched to match, right? Thanks for your help!

**Comment by cppforlife** [comment]
Updated docs-bosh repo to have latest document. Also updated init-aws to use example range. Thanks!
