### ISSUE TITLE
"ssh: no common algorithms" problem

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/bosh-init#33]
Hello.

I just get this error using `bosh-init`:
```
[main] 2015/06/02 16:27:27 ERROR - Command 'deploy' failed: Deploying: Creating instance 'bosh/0': Waiting until instance is ready: Starting SSH tunnel: Failed to connect to remote server: ssh: handshake failed: ssh: no common algorithms

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Waiting until instance is ready:
        Starting SSH tunnel:
          Failed to connect to remote server:
            ssh: handshake failed: ssh: no common algorithms
```

Some time ago I was able to fix this error by adding to /etc/ssh/sshd_config  `aes128-ctr` cipher and `hmac-sha1` MAC. I use stemcell with 2905 build number, version of go is `go1.4.2 gccgo (GCC) 5.1.0`.

The same issue occurred in [cf-ssh](https://github.com/cloudfoundry-community/cf-ssh#why-require-ssh-cli) project and they fixed it by using calling `ssh` as a system command.

Do you know a way to solve this issue quickly? Do you think that stemcell have to be updated?

**Comment by allomov** [comment]
[Here](https://github.com/golang/go/issues/10274) is a discussion for this issue in golang/go repo.

**Comment by cppforlife** [comment]
Stemcell 2915 fixes this problem.

**Comment by allomov** [comment]
@cppforlife thank you.
