### ISSUE TITLE
Suggest to remove Line 49 in templatescompiler/job_list_renderer.go

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry/bosh-init#38]
Suggest to remove Line 49 in templatescompiler/job_list_renderer.go.
https://github.com/cloudfoundry/bosh-init/blob/7ac660daf034bd293ed37e44c5a3a97e99624c06/templatescompiler/job_list_renderer.go#L48-L49

It is better to keep temporary files for advanced debug if an error occurs.

**Comment by cppforlife** [comment]
Fixed by https://github.com/cloudfoundry/bosh-init/commit/9e51b8934ff8390ad1ed6803189a93c44aebb930

**Comment by cppforlife** [comment]
After thinking a bit about it I think we should still remove the files, but may be provide a better error output when error happens.
