### ISSUE TITLE
ruby prerequisite ?

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/bosh-init#40]
Just trying to use bosh-init on a new vm, following bosh-init install step.
Seem to require ruby?

Command 'deploy' failed:
  Installing CPI:
    Rendering and uploading Jobs:
      Rendering job templates for installation:
        Rendering templates for job 'cpi/c2e7587fc42a085d406e63ac23fb0de84391809a':
          Rendering template src: application.yml.erb, dst: config/application.yml:
            Rendering template src: /root/work/.bosh_init/installations/cad807cd-9518-4866-5c74-a7f8406c5659/tmp/bosh-init-release727818083/extracted_jobs/cpi/templates/application.yml.erb, dst: /root/work/.bosh_init/installations/cad807cd-9518-4866-5c74-a7f8406c5659/tmp/rendered-jobs136182778/config/application.yml:
              Running ruby to render templates:
                Starting command ruby /root/work/.bosh_init/installations/cad807cd-9518-4866-5c74-a7f8406c5659/tmp/erb-renderer703006993/erb-render.rb /root/work/.bosh_init/installations/cad807cd-9518-4866-5c74-a7f8406c5659/tmp/erb-renderer703006993/erb-context.json /root/work/.bosh_init/installations/cad807cd-9518-4866-5c74-a7f8406c5659/tmp/bosh-init-release727818083/extracted_jobs/cpi/templates/application.yml.erb /root/work/.bosh_init/installations/cad807cd-9518-4866-5c74-a7f8406c5659/tmp/rendered-jobs136182778/config/application.yml:
                  exec: "ruby": executable file not found in $PATH

**Comment by cppforlife** [comment]
Yup, currently needs any ruby executable to build some ERB templates. Which OS are you using? Typically some ruby is available.

**Comment by poblin-orange** [comment]
ubuntu 14, just installed ruby it from apt repo, works like a charm. Just suggesting adding it to the prerequisites of bosh-init.

**Comment by cppforlife** [comment]
Updated docs: http://bosh.io/docs/install-bosh-init.html. Thanks!
