### ISSUE TITLE
bosh.io stemcell hashes are shown in md5 while bosh-init requires sha1

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-init#41]
When you include a new stemcell in your manifest, e.g. from http://bosh.io/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent you have to put the sha1 into your bosh-init manifest. However, the page only lists an md5 hash whereas for bosh releases sha1 hashes are listed.

I didn't find a way to specify manifest hashes as md5, so either this option should be added to bosh-init or the shown hashes on bosh.io should be in sha1.

**Comment by bosh-init-concourse** [comment]
We are planning to make our CI send sha1s to the bosh.io. Stay tuned.

**Comment by axelaris** [comment]
+1

**Comment by RiaanLab** [comment]
+1

**Comment by penrod** [comment]
+1

**Comment by geofffranks** [comment]
+15

**Comment by drnic** [comment]
Dmitriy, which repo is generating the wrong sha? Perhaps one of the +15 people can then PR a fix.

**Comment by weberstephanhd** [comment]
+16

I need that, too.

**Comment by cppforlife** [comment]
It's not a repo per se but our jenkins pipelines dont produce and send sha1s to bosh.io. I'll bump this in priority.

**Comment by nctiggy** [comment]
I hate to pile on, but this would nice ;)

**Comment by vital-st1x** [comment]
+1

**Comment by sklevenz** [comment]
+1

**Comment by filefrog** [comment]
Just lost about 30 minutes to this.

+1

**Comment by longnguyen11288** [comment]
+1

**Comment by thegullion** [comment]
+1

**Comment by geofffranks** [comment]
Pretty please can we have this in 2016?

**Comment by drnic** [comment]
@cppforlife can there be a tracker URL for this please so we can see if/where its in the backlog?

**Comment by schabiyo** [comment]
+1

**Comment by bs-sdev** [comment]
Still not available?

**Comment by mtekel** [comment]
7 months and still no fix?

**Comment by SimyungYang** [comment]
Please fix this issue. :)

**Comment by ematpl** [comment]
+1: I'd like this to simplify the bosh-init instructions in https://github.com/cloudfoundry-incubator/diego-release/tree/develop/examples/aws#stubsbosh-initstemcellyml. I'd prefer for bosh.io to display the SHA checksums, so https://github.com/cppforlife/bosh-hub/issues/7 is also relevant.

**Comment by crawsible** [comment]
+1. Come on, dawgs.

**Comment by cwlbraa** [comment]
# +1 please?

**Comment by virtmerlin** [comment]
+1 Cough Cough ... Still Only See md5 on bosh.io

**Comment by geofffranks** [comment]
Dmitriy et al are working on this, but it's going to be a gradual migration of stem cells. To help ease the transition, https://stemcell-sha1s.starkandwayne.com/<stem cell name>/<version> will spit back the sha1 of the stemcell.

It only goes back to about 3215, but should be getting auto-updated as new stem cells come out.

**Comment by combor** [comment]
No `sha` for stemcells makes me sad...

![image](https://cloud.githubusercontent.com/assets/163394/16650361/a9e4478c-4435-11e6-9563-400962b7e572.png)

**Comment by cppforlife** [comment]
bosh.io will now show sha1s for 3262.2+ stemcells.
