### ISSUE TITLE
[question] Blobstore URL for bosh-init

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-init#45]
This is more a question than an issue. The documentation at https://github.com/cloudfoundry/bosh-init/blob/master/docs/cli_workflow.md#12-sending-apply-message states
```
The agent serves a blobstore at `<mbus URL>/blobs` endpoint.
```

Is that really the case? In my understanding, the blobstore has a different port (as you can also see in the manifest). Nats, being used as the message bus, doesn't really provide any means to store blobs, right? So how does it actually work that blobs are being transferred and served? Can somebody please clarify the above sentence from the documentation?
Thanks!

**Comment by cppforlife** [comment]
NATS is not used by the bosh-init. 

Agent is configured to use https transport when working with bosh-init (via `mbus: "https://mbus:mbus-password@ELASTIC-IP:6868"`). Agent in that mode has `/blobs` endpoint. In NATS mode it does not provide that functionality.

In full Director scenario all agents on deployed VMs are in NATS mode and that's we rely on a dav/external blobstore, from which agents can download blobs.

We are planning to clean up some of these mechanics soon when we switch from NATS to https for all communication, even between Director and agents.

**Comment by voelzmo** [comment]
Thanks for clarifying @cppforlife. I guess I'll undo my NATS related changes in https://github.com/cloudfoundry/bosh-init/commit/dbcac78246e5de481b11d22db16eaa81b039ffc7 – sorry for messing that up.
