### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by mmoralesmc** [cloudfoundry/bosh-init#48]
Hi! I'm new in this. I'm following this tutorial https://bosh.io/docs/init-aws.html#create-key-pair
 When I come to deploy bosh-init deploy ./bosh.yml, gives me the following error
Deployment manifest: '/Users/mariamoralesmunoz/my-bosh/bosh.yml'
Deployment state: '/Users/mariamoralesmunoz/my-bosh/bosh-state.json'

Started validating
Failed validating (00:00:00)

Command 'deploy' failed:
  Parsing release set manifest '/Users/mariamoralesmunoz/my-bosh/bosh.yml':
    Unmarshalling release set manifest:
      yaml: line 7: did not find expected key

The ml file is the tutoríal, is the next:
```
---
name: bosh

releases:
- name: bosh
url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=214
sha1: c155e2d5396cf56c1e6819962e17ff5386693663
- name: bosh-aws-cpi
url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=32
sha1: 493cbeca30328546c6d966393c9f38f0f2ab6eb1

resource_pools:
- name: vms
network: private
stemcell:
url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3012
sha1: 3380b55948abe4c437dee97f67d2d8df4eec3fc1
cloud_properties:
instance_type: m3.xlarge
ephemeral_disk: {size: 25_000, type: gp2}
availability_zone: us-west-2a # <--- Replace with Availability Zone

disk_pools:
- name: disks
disk_size: 20_000
cloud_properties: {type: gp2}

networks:
- name: private
type: manual
subnets:
- range: 10.0.0.0/24
gateway: 10.0.0.1
dns: [10.0.0.2]
cloud_properties: {subnet: subnet-531f3a36} # <--- Replace with Subnet ID
- name: public
type: vip

jobs:
- name: bosh
instances: 1

templates:
- {name: nats, release: bosh}
- {name: redis, release: bosh}
- {name: postgres, release: bosh}
- {name: blobstore, release: bosh}
- {name: director, release: bosh}
- {name: health_monitor, release: bosh}
- {name: registry, release: bosh}
- {name: cpi, release: bosh-aws-cpi}

resource_pool: vms
persistent_disk_pool: disks

networks:
- name: private
static_ips: [10.0.0.6]
default: [dns, gateway]
- name: public
static_ips: [54.186.242.170] # <--- Replace with Elastic IP

properties:
nats:
address: 127.0.0.1
user: nats
password: nats-password

redis:
listen_address: 127.0.0.1
address: 127.0.0.1
password: redis-password

postgres: &db
listen_address: 127.0.0.1
host: 127.0.0.1
user: postgres
password: postgres-password
database: bosh
adapter: postgres

registry:
address: 10.0.0.6
host: 10.0.0.6
db: *db
http: {user: admin, password: admin, port: 25777}
username: admin
password: admin
port: 25777

blobstore:
address: 10.0.0.6
port: 25250
provider: dav
director: {user: director, password: director-password}
agent: {user: agent, password: agent-password}

director:
address: 127.0.0.1
name: my-bosh
db: *db
cpi_job: cpi
max_threads: 10
user_management:
provider: local
local:
users:
- {name: admin, password: admin}
- {name: hm, password: hm-password}

hm:
director_account: {user: hm, password: hm-password}
resurrector_enabled: true

aws: &aws
access_key_id: ... # <--- Replace with AWS Access Key ID
secret_access_key: ... # <--- Replace with AWS Secret Key
default_key_name: bosh
default_security_groups: [bosh]
region: us-east-1

agent: {mbus: "nats://nats:nats-password@10.0.0.6:4222"}

ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
template: {name: cpi, release: bosh-aws-cpi}

ssh_tunnel:
host: 54.186.242.170 # <--- Replace with your Elastic IP address
port: 22
user: vcap
private_key: ./bosh.pem # Path relative to this manifest file

mbus: "54.186.242.170" # <--- Replace with Elastic IP

properties:
aws: *aws
agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
ntp: *ntp
```

Someone can help me please?

Thanks so much

**Comment by allomov** [comment]
Hi @mmoralesmc.

I need to tell you VERY important thing now: first of all you need to change your access keys to AWS, because using your manifest everyone can take advantage of your account.

**Comment by allomov** [comment]
That's really important for this moment.

**Comment by allomov** [comment]
The problem that you have with your manifest now is in its layout. Since layout is broken by github output, it's hard to say what's wrong. You may want to use [gist](gist.github.com) or [github markdown](https://help.github.com/articles/github-flavored-markdown/) to share manifest better.

To check manually what's wrong you may want to use some yaml lint tool like [this](https://github.com/Pryz/yaml-lint).

**Comment by mmoralesmc** [comment]
Thanks so much @allomov

**Comment by mmoralesmc** [comment]
Hi again

Have you some tutoríal?

Thanks so much

2015-10-16 10:04 GMT+02:00 Alexander Lomov <notifications@github.com>:

> The problem that you have with your manifest now is in its layout. Since
> layout is broken by github output, it's hard to say what's wrong. You may
> want to use gist <http://gist.github.com> or github markdown
> <https://help.github.com/articles/github-flavored-markdown/> to share
> manifest better.
>
> To check manually what's wrong you may want to use some yaml lint tool
> like this <https://github.com/Pryz/yaml-lint>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-init/issues/48#issuecomment-148644692>
> .
>



--

**Comment by allomov** [comment]
The best I can give you is here http://bosh.io/docs/init-aws.html

**Comment by allomov** [comment]
But the problem most likely was in layout of your manifest. Try to parse your yaml file with lint tool.

**Comment by mmoralesmc** [comment]
This tutorial is I follow it and is the error preview... :(

2015-10-16 10:35 GMT+02:00 Alexander Lomov <notifications@github.com>:

> But the problem most likely was in layout of your manifest. Try to parse
> your yaml file with lint tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-init/issues/48#issuecomment-148653513>
> .
>



--

**Comment by mmoralesmc** [comment]
With this tool? https://en.wikipedia.org/wiki/Lint_(software)


2015-10-16 10:36 GMT+02:00 Maria Morales <maria.morales@233gradosdeti.com>:

> This tutorial is I follow it and is the error preview... :(
>
> 2015-10-16 10:35 GMT+02:00 Alexander Lomov <notifications@github.com>:
>
>> But the problem most likely was in layout of your manifest. Try to parse
>> your yaml file with lint tool.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cloudfoundry/bosh-init/issues/48#issuecomment-148653513>
>> .
>>
>
>
>
> --
>
>


--

**Comment by mmoralesmc** [comment]
With this tools http://www.yamllint.com, I have the next error to pase

(<unknown>): did not find expected key while parsing a block mapping at
line 2 column 1

2015-10-16 10:38 GMT+02:00 Maria Morales <maria.morales@233gradosdeti.com>:

> With this tool? https://en.wikipedia.org/wiki/Lint_(software)
>
>
> 2015-10-16 10:36 GMT+02:00 Maria Morales <maria.morales@233gradosdeti.com>
> :
>
>> This tutorial is I follow it and is the error preview... :(
>>
>> 2015-10-16 10:35 GMT+02:00 Alexander Lomov <notifications@github.com>:
>>
>>> But the problem most likely was in layout of your manifest. Try to parse
>>> your yaml file with lint tool.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/cloudfoundry/bosh-init/issues/48#issuecomment-148653513>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>
>
> --
>
>


--

**Comment by cppforlife** [comment]
@mmoralesmc Please make a gist so that we can see exact indentation that you have in your manifest. Example from bosh.io is correct is terms on indentation.

**Comment by allomov** [comment]
@mmoralesmc as far as I can see, you've updated manifest in your first message using github manifest. The manifest you put there does not correspond specification of yaml file. Please, check how yaml files should be formatted [here](http://docs.ansible.com/ansible/YAMLSyntax.html) or on [wiki](https://en.wikipedia.org/wiki/YAML).

**Comment by mmoralesmc** [comment]
I get not solve the error :(:(

**Comment by cppforlife** [comment]
Make sure that YAML file is valid. If the following command fails that means it's not:

```
ruby -ryaml -e 'puts YAML.load_file("<absolute path to YAML file>")
```

**Comment by allomov** [comment]
@cppforlife nice tip. I used this gem for the same purpose https://github.com/Pryz/yaml-lint (it just lets to write less symbols).
