### ISSUE TITLE
Incorrect YAML structure in microbosh.yml': Found duplicate key 'address'

### ISSUE THREAD

**Issue by mmoralesmc** [cloudfoundry/bosh-init#51]
Error to run the comand: bosh micro deployment microbosh/microbosh.yml
Incorrect YAML structure in `/Users/mariamoralesmunoz/bosh-workspace/deployments/microboshes/deployments/microbosh/microbosh.yml': Found duplicate key 'address'

Can you help me, please?

```
---
name: microbosh

logging:
level: DEBUG

network:
type: dynamic
vip: 52.22.86.70    #Change this to the allocated IP address from Step 2

resources:
persistent_disk: 20000
cloud_properties:
instance_type: m1.small
availability_zone: us-east-1a

cloud:
plugin: aws
properties:
aws:
access_key_id: ---
secret_access_key: ---
default_key_name: bosh
default_security_groups: ["bosh"]
ec2_private_key: ~/.ssh/bosh
ec2_endpoint: ec2.us-east-1.amazonaws.com
region: us-east-1

apply_spec:
agent:
blobstore:
address: 52.22.86.70    #Change this to the allocated IP address from Step 2
nats:
address: 52.22.86.70    #Change this to the allocated IP address from Step 2
properties:
aws_registry:
address: 52.22.86.70    #Change this to the allocated IP address from Step 2
```

**Comment by cppforlife** [comment]
bosh-init is the replacement for `bosh micro`. manifest above will not work with bosh-init.

**Comment by mmoralesmc** [comment]
So what should I do?

2015-10-16 18:56 GMT+02:00 Dmitriy Kalinin <notifications@github.com>:

> bosh-init is the replacement for bosh micro. manifest above will not work
> with bosh-init.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-init/issues/51#issuecomment-148769606>
> .
>



--

**Comment by cppforlife** [comment]
You can try following http://bosh.io/docs/init-aws.html to install BOSH on AWS.

**Comment by mmoralesmc** [comment]
Thanks you so much. I will try it

El lunes, 2 de noviembre de 2015, Dmitriy Kalinin <notifications@github.com>
escribió:

> You can try following http://bosh.io/docs/init-aws.html to install BOSH
> on AWS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-init/issues/51#issuecomment-152951379>
> .
>


--

**Comment by mmoralesmc** [comment]
Thanks you so much, I try it.

2015-11-02 9:35 GMT+01:00 Dmitriy Kalinin <notifications@github.com>:

> You can try following http://bosh.io/docs/init-aws.html to install BOSH
> on AWS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/bosh-init/issues/51#issuecomment-152951379>
> .
>



--
