### ISSUE TITLE
Bosh-init not compatible with vsphere-cpi release 11

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry/bosh-init#53]
https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/commit/8050c574560d87d993856dafbfff5b87c0fda465

![screen shot 2015-10-25 at 21 49 22](https://cloud.githubusercontent.com/assets/317403/10719168/491b340c-7b62-11e5-9f2e-a2d192c1e9e8.png)

**Comment by cppforlife** [comment]
See https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/releases/tag/v11

**Comment by bonzofenix** [comment]
Thank!
