### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-init#55]
Any chance you can use GitHub Releases for this project, rather than just tags? I'd like to be able to use the `github-release` concourse resource to trigger updates to our docker images based on new versions of `bosh-init`. Unfortunately right now `curl https://api.github.com/repos/cloudfoundry/bosh-init/releases` returns an empty array, so concourse doesn't find any releases to watch.

**Comment by longnguyen11288** [comment]
:+1:
