### ISSUE TITLE
Add option to Force redeploy

### ISSUE THREAD

**Issue by skibum55** [cloudfoundry/bosh-init#60]
If the BOSH instance has been stopped on AWS, it will no longer function on restart.  We propose a flag to be used with the _deploy_ command that could be used to _force_ a redeploy even though the manifest has not changed.

**Comment by cppforlife** [comment]
`bosh deploy --recreate` recreate VMs regardless if anything changes or not.

**Comment by cppforlife** [comment]
Oops. This is bosh-init repo...

**Comment by philippthun** [comment]
Also useful when the version of bosh-init has changed (and now supports e.g. pre-start scripts) and I want to redeploy my director...

**Comment by jgallucci32** [comment]
Certainly in the past 3 years there have been enough director VMs to have failed to the point they need redeployed. SO my question is...how has the community been redeploying Director VMs while we wait for a feature to do it via command line?

**Comment by dpb587-pivotal** [comment]
The upcoming version of the CLI will have a `--recreate` option (see https://github.com/cloudfoundry/bosh-cli/pull/316). Historically, you could modify the state file or deployment manifest to emulate a change.

**Comment by dpb587-pivotal** [comment]
Closing - released [v2.0.40](https://github.com/cloudfoundry/bosh-cli/releases/tag/v2.0.40) (requires bosh-cli, since bosh-init is deprecated).
