### ISSUE TITLE
Bosh init gives error, on vsphere, while deploying bosh

### ISSUE THREAD

**Issue by lotus2015** [cloudfoundry/bosh-init#63]
Hi,
I am trying to deploy bosh with 'bosh-init deploy bosh.yml'  ,When deploying I get the following error:

[2016-01-05T15:47:10.143196 #13128]  INFO -- : Powering on VM: (VSphereCloud::Resources::VM 
(cid="vm-49273c9c-5cdf-42c9-96f6-d5a11c7f1d1c"))
/root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphere_cpi_ruby/l
ib/ruby/2.1.0/json/common.rb:223:in `encode': "\xE6" on US-ASCII (Encoding::InvalidByteSequenceError)	from /root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphe
re_cpi_ruby/lib/ruby/2.1.0/json/common.rb:223:in `generate'	from /root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphe
re_cpi_ruby/lib/ruby/2.1.0/json/common.rb:223:in `generate'	from /root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphe
re_cpi_ruby/lib/ruby/2.1.0/json/common.rb:394:in `dump'	from /root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphe
re_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3093.0/lib/bosh/cpi/cli.rb:114:in `result_response'	from /root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphe
re_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3093.0/lib/bosh/cpi/cli.rb:82:in `run'	from /root/.bosh_init/installations/bbcf9320-af64-4494-6923-c8351d81aceb/packages/vsphe
re_cpi/bin/vsphere_cpi:37:in `<main>'':
            unexpected end of JSON input

**Comment by dpb587-pivotal** [comment]
This seems like the same issue as https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/issues/5
