### ISSUE TITLE
volume is not created on openstack kilo

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-init#64]
i followed the documentation on https://bosh.io/docs/init-openstack.html
and created/edited the template file accordingly
but the deployment fails because the volume is never created

i even tried 
```
- jobs
  persistent_disk: 20000
```
instead of the use
 persistent_disk_pool: disks

**Comment by cppforlife** [comment]
Closing here. Discussion continues in openstack cpi repo.
