### ISSUE TITLE
Possible to use variables in bosh-init yml

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-init#69]
In the past, we define variables at the top of yml (embraced with <%...%>) when deploying micro-bosh with bosh-cli and micro-plugin. But we found it can't work with bosh-init, is there a way to use variables in yml to deploy a micro bosh with bosh-init? Thanks.

**Comment by dpb587-pivotal** [comment]
Not currently possible with `bosh-init`. Not sure if it's a planned feature or anything.

As an alternative, you might be able to pre-parse it with something like `erb bosh-init.yml.erb > bosh-init.yml` before running your `bosh-init deploy bosh-init.yml`.

**Comment by cppforlife** [comment]
@mattcui it's not planned to add ERB rendering of manifests. we are planning to add {{..}} concourse/fly style interpolation soon.

**Comment by DonBower** [comment]
did this get implemented?

**Comment by dpb587-pivotal** [comment]
@DonBower yes, please see [this doc](http://bosh.io/docs/cli-int.html) for the new BOSH CLI.

**Comment by DonBower** [comment]
@dpb587-pivotal The Document you refer to is for Bosh CLI V2, not BOSH-INIT.

**Comment by dpb587-pivotal** [comment]
@DonBower `bosh create-env` [replaces](http://bosh.io/docs/cli-v2-diff.html) `bosh-init create` and has support for variables. This bosh-init repository is no longer maintained in favor of that.
