### ISSUE TITLE
Implement bosh v2 template accessors

### ISSUE THREAD

**Issue by keymon** [cloudfoundry/bosh-init#76]
Bosh implements a new called v2 schema, which includes some features like [links](https://bosh.io/docs/links.html). These features include [new *Template Accessors*](https://bosh.io/docs/links.html#templates):

> the link template accessor allows access to link information such as instance names, AZs, IDs, network addresses, etc.
>
>    link("...") allows access to linked instances and their properties
>    if_link("...") allows conditional access to a link (useful for optional links)

Without this feature, deployments of releases with the new features will fail. 

An example of this is concourse > v1.0.0, which includes [several jobs using the link features](https://github.com/concourse/concourse/blob/master/jobs/groundcrew/templates/worker.json.erb#L9)

**Comment by voelzmo** [comment]
As far as I know, those accessor are actually implemented already, we just need a release of bosh-init. See commit such as https://github.com/cloudfoundry/bosh-init/commit/8f2ceb9a3520b9f5d20fd7b8ee315274f38e2f3c

**Comment by keymon** [comment]
Actually this is even more complicated. Bosh-init should support all the new features in bosh (aka bosh v2), if we want to use the same manifest with bosh-init than we use with bosh.

But I think one could write a manifest that works on bosh-init even using releases with the new features

**Comment by keymon** [comment]
@voelzmo if_link is indeed implemented, but I cannot find if `link()` helper is implemented: (more info here https://github.com/cloudfoundry/bosh/blob/master/bosh-template/lib/bosh/template/evaluation_context.rb#L96)

**Comment by cppforlife** [comment]
we are not planning to implement v2 links in bosh-init. for releases like concourse which use bosh-init for a single vm, currently they'll have to keep around properties that allow non link configuration (ie if_p).

**Comment by cppforlife** [comment]
[0.0.90 implements job level properties](https://github.com/cloudfoundry/bosh-init/releases/tag/v0.0.90). if_link was also added in earlier releases. currently expected v2 compatibility in bosh-init is complete for now.
