### ISSUE TITLE
v0.0.90 bosh-init deploy fails

### ISSUE THREAD

**Issue by xchapter7x** [cloudfoundry/bosh-init#78]
the below error is seen on the latest release `v0.0.90` when running a bosh-init deploy
this issue does not exist on the prior release `v0.0.88` using `git checkout d8e5ff06604cce9592b1447062c73bd0b7014b0a`

error output below:

```
go run main.go deploy ./dep.yml
# github.com/cloudfoundry/bosh-init/deployment/vm
../.go/src/github.com/cloudfoundry/bosh-init/deployment/vm/vm.go:190: not enough arguments in call to vm.agentClient.RunScript
```

**Comment by cppforlife** [comment]
@xchapter7x according to this build: https://main.bosh-ci.cf-app.com/pipelines/bosh-init/jobs/build/builds/21 0.0.90 is produced from e7b17a6df499bc8aa54161b317a844ef4d9f988b. please check that.

**Comment by xchapter7x** [comment]
all i did was 
`go get github.com/cloudfoundry/bosh-init`
by simply checking out the `.88` release sha or the `.90` release sha i can reproduce the error.

```
#sha for v0.0.90
$ git rev-parse HEAD
e7b17a6df499bc8aa54161b317a844ef4d9f988b

$ go run main.go deploy ~/boshstuff/enam.yml
# github.com/cloudfoundry/bosh-init/deployment/vm
deployment/vm/vm.go:190: not enough arguments in call to vm.agentClient.RunScript
```


```
#sha for v0.0.88
$ git checkout d8e5ff06604cce9592b1447062c73bd0b7014b0a
$ git rev-parse HEAD
d8e5ff06604cce9592b1447062c73bd0b7014b0a

$ go run main.go deploy ~/boshstuff/enam.yml
Deployment manifest: '/Users/x7x/boshstuff/enam.yml'
Deployment state: '/Users/x7x/boshstuff/enam-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
...
```

**Comment by dpb587-pivotal** [comment]
Might want to double check you're using go1.6.1. Also using the bin/env or bin/build script which enables the newer go vendoring strategy. Sounds like your build is trying to use an outdated source.

**Comment by xchapter7x** [comment]
good call.

i didnt notice the project switched to using `vendor` from v88 to v90
i was setting the govendorexperiment=0

my bad :(

thanks for the help
