### ISSUE TITLE
Bosh-init version change is not taken into account by deploy command

### ISSUE THREAD

**Issue by philippthun** [cloudfoundry/bosh-init#89]
The deploy command checks if a release, the stemcell, or the deployment manifest has changed. I run into an issue as I had to update bosh-init (support for pre-start scripts was added with version 0.0.82) but running the deploy command resulted in a "nothing changed" message. Shouldn't the version of bosh-init be also taken into account when determining if a new deployment has to be triggered?

I've already started to work on a pull request (but cannot run the integration tests as reported [here](https://github.com/cloudfoundry/bosh-init/issues/88)) - please let me know if this is something useful that I should continue or if this is not treated as an issue.

**Comment by cppforlife** [comment]
@philippthun im not sure if it should account for the version since bosh-init records deployment info at the end of the successful procedure. i would not expect new bosh-init version to suddenly redeploy machine it has previously deployed successfully.

**Comment by voelzmo** [comment]
@cppforlife probably not re-deploy automatically. What about a switch to do so explicitly? Much like `bosh deploy --recreate`?

**Comment by philippthun** [comment]
Although for our specific setup (automated pipeline) it would be best to have this automatic redeploy mechanism, I understand that for most bosh-init users this would be strange and not expected. Thus I agree with @voelzmo that there should be a switch. So I will close this issue in favor of https://github.com/cloudfoundry/bosh-init/issues/60
