### ISSUE TITLE
Go CLI `tasks` command doesn't suggest how to see recent events

### ISSUE THREAD

**Issue by forrestsill** [cloudfoundry/bosh-init#93]
Ruby CLI:
```
bosh tasks
Acting as user 'admin' on 'my-bosh'
No running tasks
```

Go CLI:
```
bosh-init tasks
Using environment 'xxx' as user 'admin'

#  State  Created At  User  Description  Result

0 tasks

Succeeded
```

The Ruby CLI hints with red text that maybe there is a different flag to see past tasks while the Go CLI does not. It would be even better if they both pointed the user to the `--recent` flag.

**Comment by cppforlife** [comment]
No plans to fix this in the CLI aside from changing documentation.
