### ISSUE TITLE
`bosh --version` returns failure; should return success

### ISSUE THREAD

**Issue by cunnie** [cloudfoundry/bosh-init#94]
`bosh --version` returns failure (1); should return success (0).

```
$ bosh --version
version 0.0.25-daaed40-2016-08-15T18:49:02Z

Exit code 1
```

The UNIX convention is to return success when passed the `--version` flag (0); e.g.

```
tar --version; echo $?
bsdtar 2.8.3 - libarchive 2.8.3
0
```

**Comment by cppforlife** [comment]
https://github.com/jessevdk/go-flags/issues/186

**Comment by cppforlife** [comment]
Moved to https://github.com/cloudfoundry/bosh-cli/issues/2
