### ISSUE TITLE
`bosh export-release` requires -d <deployment>

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-init#99]
I don't see a reason why this needs a deployment context?

```
vcap@jumpbox:~/workspace/exported-releases$ bosh-go export-release bosh/257.3 ubuntu-trusty/3262.2
Using environment '192.168.1.11' as user 'admin'

Expected non-empty deployment name

Exit code 1
```
Same command with `-d bosh` works.

```
$ bosh-go -v
version 0.0.20-5fa85a8-2016-08-08T16:20:05Z
```

**Comment by cppforlife** [comment]
@voelzmo we need deployment to track compilation vms. for example if someone kill -9 worker then we would lose track of them without a deployment. so it's more of a namespace for all iaas resources created.
